### ISSUE TITLE
Is a broker required?

### ISSUE THREAD

**Issue by hevnsnt** [PhracturedBlue/ESP8266MQTTMesh#17]
Sorry for the probably stupid question, but I am trying to learn MQTT.

Let's say that I have three ESP8266s in a mesh using your firmware.

#1 is a motion sensor
#2 is a water sensor
#3 has a RGB Led on it

Is a MQTT broker required for the three of them to talk?  I would like when #1 triggers motion, #3 lights the LED red, and if #2 detects water, #3 lights the LED blue.  I have a high level understanding of how this would work with the broker, but is a broker required?

Also, I meant to mention. Thank you for releasing this, and making it so easy for the rest of us.  I am learning a lot with your project!

**Comment by PhracturedBlue** [comment]
This library is entirely reliant on a central broker  The only method by which nodes can talk is via an existing MQTT broker.  The broker is an integral part of this code, and even with enhandements to allow nodes to directly talk to each other (rather than through the broker), you would still need the broker to store the node ids.  If you are looking for a mesh that is fully self-hosting, you may want to look at the painlessmesh implementation.  I haven't used it myself, but I think it may be more along those lines.
