### ISSUE TITLE
Improvement Request - QoS

### ISSUE THREAD

**Issue by ibaranov-cp** [PhracturedBlue/ESP8266MQTTMesh#5]
Hello,

Are there any thoughts to implementing MQTT's understanding of Quality of Service?
This should make actions like updating firmware much more robust, if client and broker both select QoS 2.

This might actually make it faster, by eliminating the current delay between data chunks
```
        time.sleep(0.2)
```
in send_ota.py

**Comment by PhracturedBlue** [comment]
QoS is now supported for message sending (to the broker), but not for receiving.  So it still doesn't help with OTA.  Even if I implement the rest of the QoS support, it won't necessarily help with OTA though, because the OTA is meant to be a broadcast message and QoS won't tell you when all nodes have received a message.
