### ISSUE TITLE
QOS

### ISSUE THREAD

**Issue by eporocrail** [PhracturedBlue/ESP8266MQTTMesh#66]
Make sure you have the latest version of ESP8266MQTTMesh before reporting an issue.

I am using the Arduino IDE.

When I send using
mesh.publish(topicPub, msgTX.c_str(), MSG_TYPE_QOS_2);

the response =

[onWifiConnect] Connecting to mqtt
[connect_mqtt] Attempting MQTT connection (192.168.2.1:1883)...
[onMqttConnect] MQTT Connected
[publish] Sending: 43a0d4=02:19:82:43:A0:D4
[setup_AP] Initialized AP as 'eltraco_mesh_43a0d4'  IP '192.168.3.1'
Subscribe acknowledged.
  packetId: 1
  qos: 0

This suggests that although ordered otherwise QOS0 is used.

Is my perception alright and if so there might be some work required.

regards
eporocrail

**Comment by simone1999** [comment]
hi,
if I am right the Output you sent doesn't show the message you sent at all, because your Log only shows the Connection Process, the Message you sent should appear in the Serial Window as [publish].
The qos: 0 therefore is not relatet to the Message you sent but relatet to the subscription QOS for receiving Messages from the Broker
